elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Dhttp.max_content_length=512M -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
#  image: logstash:latest
  build: logstash/
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  #command: logstash -f /etc/logstash/conf.d/logstash.conf
  command: bash -c "LS_HEAP_SIZE=2048m logstash -f /etc/logstash/conf.d/logstash.conf"
  ports:
    - "8000:8000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
